const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process'),{once}=require('node:events'),{pathToFileURL}=require('node:url'),{chromium}=require('../../node_modules/playwright');
(async()=>{execFileSync('ffmpeg',['-version'],{stdio:'ignore'});execFileSync('ffprobe',['-version'],{stdio:'ignore'});const browser=await chromium.launch({executablePath:process.env.HPS_CHROME});try{
  const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await page.evaluate(()=>watercolorReady);
  await page.addStyleTag({content:'main{margin:0;padding:0;max-width:none}header,.controls,.meta{display:none}.frame{width:1280px;box-shadow:none}'});await page.waitForTimeout(80);
  const directory=path.resolve(__dirname,'../../../outputs/handdrawn-watercolor-v1');fs.mkdirSync(directory,{recursive:true});const name='watercolor-'+crypto.randomUUID(),temp=path.join(directory,name+'.partial.mp4'),final=path.join(directory,name+'.mp4');
  const fps=24,frames=288,encoder=spawn('ffmpeg',['-hide_banner','-loglevel','error','-f','image2pipe','-vcodec','png','-framerate',String(fps),'-i','pipe:0','-an','-c:v','libx264','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',temp],{stdio:['pipe','ignore','pipe'],windowsHide:true});let log='';encoder.stderr.on('data',b=>log=(log+b.toString()).slice(-4096));encoder.stdin.on('error',()=>{});const closed=once(encoder,'close');
  for(let i=0;i<frames;i++){await page.evaluate(t=>watercolorScene.renderAt(t),i*1000/fps);if(!encoder.stdin.write(await page.locator('#frame').screenshot()))await Promise.race([once(encoder.stdin,'drain'),closed.then(()=>{throw new Error(log||'Encoder closed')})]);if(i%96===0)console.log(`Export ${i}/${frames}`)}
  encoder.stdin.end();const [code]=await closed;assert.equal(code,0,log);const info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',temp],{encoding:'utf8'}));assert.equal(info.streams.length,1);assert.equal(Number(info.streams[0].nb_frames),frames);assert.equal(info.streams[0].width,1280);assert.equal(info.streams[0].height,720);execFileSync('ffmpeg',['-v','error','-i',temp,'-f','null','-'],{stdio:'pipe'});fs.renameSync(temp,final);
  fs.writeFileSync(path.join(__dirname,'evidence/video.json'),JSON.stringify({file:path.basename(final),directory:'outputs/handdrawn-watercolor-v1',durationSeconds:12,fps,frames,width:1280,height:720,audio:false,subtitleZone:{top:800,height:100,logicalCanvas:'1600x900'},subtitleFont:32,sha256:crypto.createHash('sha256').update(fs.readFileSync(final)).digest('hex'),decode:'passed'},null,2)+'\n');console.log(final);
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
