const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {pathToFileURL}=require('node:url'),{chromium}=require('../../node_modules/playwright');
const base=__dirname,evidence=path.join(base,'evidence'),hash=buf=>crypto.createHash('sha256').update(buf).digest('hex');
(async()=>{fs.mkdirSync(evidence,{recursive:true});const browser=await chromium.launch({executablePath:process.env.HPS_CHROME});try{
  const page=await browser.newPage({viewport:{width:1600,height:1020},deviceScaleFactor:1});const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(pathToFileURL(path.join(base,'atlas.html')).href);await page.evaluate(()=>atlasReady);await page.screenshot({path:path.join(evidence,'atlas.png'),fullPage:true});
  await page.goto(pathToFileURL(path.join(base,'index.html')).href);await page.evaluate(()=>window.watercolorReady || Promise.reject(new Error(document.querySelector("#status")?.textContent+" / "+JSON.stringify(window.WatercolorEffects?.version)))).catch(e=>{throw new Error(e.message+" / "+errors.join("; "))});
  const frames=[];for(const t of [0,2400,5200,8000,12000]){await page.evaluate(t=>watercolorScene.renderAt(t),t);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const first=await page.locator('#frame').screenshot();await page.evaluate(()=>watercolorScene.renderAt(0));await page.evaluate(t=>watercolorScene.renderAt(t),t);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(hash(first),hash(await page.locator('#frame').screenshot()));fs.writeFileSync(path.join(evidence,`frame-${t}.png`),first);frames.push({timeMs:t,sha256:hash(first)});}
  const zones=await page.evaluate(()=>{const content=document.querySelector('#content'),subtitle=document.querySelector('#subtitle-zone');const c=content.getBoundingClientRect(),s=subtitle.getBoundingClientRect();return {contentHeight:content.offsetHeight,subtitleTop:subtitle.offsetTop,subtitleHeight:subtitle.offsetHeight,noOverlap:c.bottom<=s.top,objectsClear:[...content.children].filter(x=>x.classList.contains('object')||x.classList.contains('beaker')||x.classList.contains('callout')||x.classList.contains('small-note')).every(x=>x.getBoundingClientRect().bottom<=s.top),assetAlpha:document.querySelector('#beaker').naturalWidth>0}});assert.deepEqual(zones,{contentHeight:800,subtitleTop:800,subtitleHeight:100,noOverlap:true,objectsClear:true,assetAlpha:true});
  const subtitle=await page.evaluate(()=>{const results=[];for(const size of [20,32,44]){watercolorScene.setSubtitleFont(size);for(const t of [0,2700,6500,9500]){watercolorScene.renderAt(t);const box=document.querySelector('#subtitle-zone');results.push(box.scrollWidth<=box.clientWidth&&box.scrollHeight<=box.clientHeight)}}watercolorScene.setSubtitleFont(32);return results.every(Boolean)});assert.ok(subtitle);
  const invalid=await page.evaluate(()=>{const host=document.createElement('div');document.body.append(host);const cases=[()=>WatercolorEffects.mount(host,'label',{width:160,height:70,text:'这是一个很长很长的标签',fontSize:42}),()=>WatercolorEffects.mount(host,'icon',{width:50,height:60}),()=>WatercolorEffects.mount(host,'icon',{width:100,height:100,icon:'wrong'})];const passed=cases.every(run=>{try{run();return false}catch{return true}});host.remove();return passed});assert.ok(invalid);
  await page.locator('#play').click();await page.waitForTimeout(500);assert.ok(await page.evaluate(()=>watercolorScene.time>250&&watercolorScene.playing));await page.locator('#pause').click();const paused=await page.evaluate(()=>watercolorScene.time);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>watercolorScene.time),paused);
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify({effectVersion:'0.1.0',frames,zones,subtitleSizes:[20,32,44],invalidInputsRejected:3,realPlayback:'passed',pause:'passed',pageErrors:errors,browser:browser.version(),visualReview:'agent-inspected; user review pending'},null,2)+'\n');console.log('Watercolor atlas, 5 deterministic frames, subtitle zone, playback and pause passed.');
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
