const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('static/annotations_workspace.js', 'utf8');
const flow = source.slice(source.indexOf('function renderAnnotationFlow('), source.indexOf('function renderAnnotationItems('));
const nodes = new Map();
function node(phase) { return {dataset:{annotationPhase:String(phase)},classList:{toggle(name,on){this[name]=on;}},setAttribute(name,value){this[name]=value;},removeAttribute(name){delete this[name];}}; }
const phases=[1,2,3].map(node);
['annotation-result-count','annotation-next-action','annotation-confirm-hint','annotation-btn-ai-plan','annotation-btn-ai-all','annotation-btn-preview','annotation-stage-feedback','annotation-btn-confirm-page'].forEach(id=>nodes.set(id,node(0)));
const context = {ANNOTATIONS_WS:{page:{items:[]},activeJob:null},document:{getElementById:id=>nodes.get(id),querySelectorAll:()=>phases}};
vm.createContext(context);vm.runInContext(flow,context);
context.renderAnnotationFlow();
assert.equal(phases[0]['aria-current'],'step');
assert.equal(nodes.get('annotation-btn-confirm-page').disabled,true);
assert.equal(nodes.get('annotation-btn-ai-plan').textContent,'AI 勾画本页');
context.ANNOTATIONS_WS.page.items=[{status:{content:'draft'}},{status:{content:'disabled'}}];
context.renderAnnotationFlow();
assert.equal(phases[1]['aria-current'],'step');
assert.equal(nodes.get('annotation-result-count').textContent,'1 处勾画 · 0/1 已确认');
assert.equal(nodes.get('annotation-btn-preview').classList['annotation-recommended-action'],true);
context.ANNOTATIONS_WS.activeJob={operation:'align'};
context.renderAnnotationFlow();
assert.equal(nodes.get('annotation-btn-ai-plan').disabled,true);
assert.equal(nodes.get('annotation-btn-confirm-page').disabled,true);
assert.equal(nodes.get('annotation-stage-feedback').hidden,false);
assert.match(nodes.get('annotation-stage-feedback').textContent,/匹配语音/);
context.ANNOTATIONS_WS.activeJob=null;
context.ANNOTATIONS_WS.page.items[0].status.content='confirmed';
context.renderAnnotationFlow();
assert.equal(phases[2]['aria-current'],'step');
assert.equal(nodes.get('annotation-result-count').textContent,'1 处勾画 · 1/1 已确认');
assert.equal(nodes.get('annotation-btn-ai-plan').disabled,false);
assert.equal(nodes.get('annotation-stage-feedback').hidden,true);
console.log('annotation flow presentation checks passed');
